/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as VideoFilesRouteImport } from './routes/video-files'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as TagTypesRouteImport } from './routes/tag-types'
import { Route as FileDirsRouteImport } from './routes/file-dirs'
import { Route as DistributorsRouteImport } from './routes/distributors'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as ActorsRouteImport } from './routes/actors'
import { Route as IndexRouteImport } from './routes/index'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoFilesRoute = VideoFilesRouteImport.update({
  id: '/video-files',
  path: '/video-files',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTypesRoute = TagTypesRouteImport.update({
  id: '/tag-types',
  path: '/tag-types',
  getParentRoute: () => rootRouteImport,
} as any)
const FileDirsRoute = FileDirsRouteImport.update({
  id: '/file-dirs',
  path: '/file-dirs',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorsRoute = DistributorsRouteImport.update({
  id: '/distributors',
  path: '/distributors',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsRoute = ActorsRouteImport.update({
  id: '/actors',
  path: '/actors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actors': typeof ActorsRoute
  '/creators': typeof CreatorsRoute
  '/distributors': typeof DistributorsRoute
  '/file-dirs': typeof FileDirsRoute
  '/tag-types': typeof TagTypesRoute
  '/tags': typeof TagsRoute
  '/video-files': typeof VideoFilesRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actors': typeof ActorsRoute
  '/creators': typeof CreatorsRoute
  '/distributors': typeof DistributorsRoute
  '/file-dirs': typeof FileDirsRoute
  '/tag-types': typeof TagTypesRoute
  '/tags': typeof TagsRoute
  '/video-files': typeof VideoFilesRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actors': typeof ActorsRoute
  '/creators': typeof CreatorsRoute
  '/distributors': typeof DistributorsRoute
  '/file-dirs': typeof FileDirsRoute
  '/tag-types': typeof TagTypesRoute
  '/tags': typeof TagsRoute
  '/video-files': typeof VideoFilesRoute
  '/videos': typeof VideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actors'
    | '/creators'
    | '/distributors'
    | '/file-dirs'
    | '/tag-types'
    | '/tags'
    | '/video-files'
    | '/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actors'
    | '/creators'
    | '/distributors'
    | '/file-dirs'
    | '/tag-types'
    | '/tags'
    | '/video-files'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/actors'
    | '/creators'
    | '/distributors'
    | '/file-dirs'
    | '/tag-types'
    | '/tags'
    | '/video-files'
    | '/videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActorsRoute: typeof ActorsRoute
  CreatorsRoute: typeof CreatorsRoute
  DistributorsRoute: typeof DistributorsRoute
  FileDirsRoute: typeof FileDirsRoute
  TagTypesRoute: typeof TagTypesRoute
  TagsRoute: typeof TagsRoute
  VideoFilesRoute: typeof VideoFilesRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-files': {
      id: '/video-files'
      path: '/video-files'
      fullPath: '/video-files'
      preLoaderRoute: typeof VideoFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag-types': {
      id: '/tag-types'
      path: '/tag-types'
      fullPath: '/tag-types'
      preLoaderRoute: typeof TagTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-dirs': {
      id: '/file-dirs'
      path: '/file-dirs'
      fullPath: '/file-dirs'
      preLoaderRoute: typeof FileDirsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributors': {
      id: '/distributors'
      path: '/distributors'
      fullPath: '/distributors'
      preLoaderRoute: typeof DistributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors': {
      id: '/actors'
      path: '/actors'
      fullPath: '/actors'
      preLoaderRoute: typeof ActorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActorsRoute: ActorsRoute,
  CreatorsRoute: CreatorsRoute,
  DistributorsRoute: DistributorsRoute,
  FileDirsRoute: FileDirsRoute,
  TagTypesRoute: TagTypesRoute,
  TagsRoute: TagsRoute,
  VideoFilesRoute: VideoFilesRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
