/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as VideosIdRouteImport } from './routes/videos.$id'
import { Route as TagsIdRouteImport } from './routes/tags.$id'
import { Route as CreatorsIdRouteImport } from './routes/creators.$id'
import { Route as ActorsIdRouteImport } from './routes/actors.$id'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VideosRoute,
} as any)
const VideosIdRoute = VideosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VideosRoute,
} as any)
const TagsIdRoute = TagsIdRouteImport.update({
  id: '/tags/$id',
  path: '/tags/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsIdRoute = CreatorsIdRouteImport.update({
  id: '/creators/$id',
  path: '/creators/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsIdRoute = ActorsIdRouteImport.update({
  id: '/actors/$id',
  path: '/actors/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/videos': typeof VideosRouteWithChildren
  '/actors/$id': typeof ActorsIdRoute
  '/creators/$id': typeof CreatorsIdRoute
  '/tags/$id': typeof TagsIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/videos/': typeof VideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actors/$id': typeof ActorsIdRoute
  '/creators/$id': typeof CreatorsIdRoute
  '/tags/$id': typeof TagsIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/videos': typeof VideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/videos': typeof VideosRouteWithChildren
  '/actors/$id': typeof ActorsIdRoute
  '/creators/$id': typeof CreatorsIdRoute
  '/tags/$id': typeof TagsIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/videos/': typeof VideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/videos'
    | '/actors/$id'
    | '/creators/$id'
    | '/tags/$id'
    | '/videos/$id'
    | '/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actors/$id'
    | '/creators/$id'
    | '/tags/$id'
    | '/videos/$id'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/videos'
    | '/actors/$id'
    | '/creators/$id'
    | '/tags/$id'
    | '/videos/$id'
    | '/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VideosRoute: typeof VideosRouteWithChildren
  ActorsIdRoute: typeof ActorsIdRoute
  CreatorsIdRoute: typeof CreatorsIdRoute
  TagsIdRoute: typeof TagsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof VideosRoute
    }
    '/videos/$id': {
      id: '/videos/$id'
      path: '/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof VideosIdRouteImport
      parentRoute: typeof VideosRoute
    }
    '/tags/$id': {
      id: '/tags/$id'
      path: '/tags/$id'
      fullPath: '/tags/$id'
      preLoaderRoute: typeof TagsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$id': {
      id: '/creators/$id'
      path: '/creators/$id'
      fullPath: '/creators/$id'
      preLoaderRoute: typeof CreatorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors/$id': {
      id: '/actors/$id'
      path: '/actors/$id'
      fullPath: '/actors/$id'
      preLoaderRoute: typeof ActorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VideosRouteChildren {
  VideosIdRoute: typeof VideosIdRoute
  VideosIndexRoute: typeof VideosIndexRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosIdRoute: VideosIdRoute,
  VideosIndexRoute: VideosIndexRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VideosRoute: VideosRouteWithChildren,
  ActorsIdRoute: ActorsIdRoute,
  CreatorsIdRoute: CreatorsIdRoute,
  TagsIdRoute: TagsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
