export enum ErrorCode {
  VALIDATION = "VALIDATION",
  FOREIGN_KEY_VIOLATION = "FOREIGN_KEY_VIOLATION",
  UNIQUE_VIOLATION = "UNIQUE_VIOLATION",
  TAG_TYPE_NOT_FOUND = "TAG_TYPE_NOT_FOUND",
  NOT_FOUND = "NOT_FOUND",
  UNKNOWN = "UNKNOWN",
}